### ISSUE TITLE
Results not being produced for some samples

### ISSUE THREAD

**Issue by ammaraziz** [grubaughlab/DENV_pipeline#10]
Hi there,

Thank you for both the DengueSeq protocol and this pipeline. We've (VIDRL-Australia) used both for sequencing Dengue 2 and it's working wonderfully.

We ran 20 samples through the pipeline, a few did not generate any consensus due to lack of reads (samples had high Ct values), with the rest generating a consensus apart from two samples. These two samples had plenty of reads, great depth, were included in the summary files (eg top_virus_all_samples.tsv) but they do not appear anywhere in the alignments/consensus/bam folders.

I thought I was going a tad crazy, so I reran just the two samples giving me trouble and yep, the data is generated by never moved into the results folder. I ran the pipeline again with the --temp flag, everything is there.

Any assistance would be appreciated. I can send the pipeline output via a link (can't share in the open unfortunately).

Thanks,

Ammar

**Comment by ammaraziz** [comment]
Dug a little deeper into the pipeline, looks like results folder is created from finding `_all_virustype_info.txt` files. For the two missing samples, these are created in the temp directory and do contain data.

This is the content of one of those that didnt copy to the results folder:

```
SAMPLENAME     SAMPLENAME.DENV1.10.cons.fa    10      NA      NA      10735   640     5.96    5.01
SAMPLENAME     SAMPLENAME.DENV2.10.cons.fa    10      DENV2   DENV2.fasta     10723   10299   96.05   97.91
SAMPLENAME     SAMPLENAME.DENV3.10.cons.fa    10      NA      NA      10707   519     4.85    4.65
SAMPLENAME     SAMPLENAME.DENV4.10.cons.fa    10      Unknown NA      NA      NA      0       0
SAMPLENAME     SAMPLENAME.DENV2_sylvatic.10.cons.fa   10      NA      NA      10722   5388    50.25   49.93
SAMPLENAME     SAMPLENAME.DENV4_sylvatic.10.cons.fa   10      NA      NA      10667   216     2.02    1.66
```

**Comment by ViralVerity** [comment]
Hi, thanks for the feedback!

This is interesting - I did rejig how the temporary vs results files are made recently, so I suspect I've introduced a bug. Is it possible for you to send me the fastq files so I can test it? And the bed files (if you're not using the default ones)

You can send them to verity.hill@yale.edu

Thanks!

**Comment by ViralVerity** [comment]
I think I've fixed this! Give it a pull and see if it works with your input files

**Comment by ammaraziz** [comment]
Apologies for not replying. Thank you for fixing this issue. I haven't experienced the above issue on newer samples. Using it for Solomon sequencing!
