### ISSUE TITLE
ONT compatible?

### ISSUE THREAD

**Issue by kneubehl** [grubaughlab/DENV_pipeline#17]
This pipeline seems to rely on Illumina paired end data and mapping with bwa only correct? So this would not be compatible with ONT data?

**Comment by ViralVerity** [comment]
That is all correct, but here is a pipeline which our collaborators wrote which will handle ONT: https://github.com/josephfauver/DENV_MinION_Script

**Comment by kneubehl** [comment]
Thanks!
