### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by ammaraziz** [grubaughlab/DENV_pipeline#18]
Hi there,

We've sequenced a bunch of samples from the solomons using DengueSeq and this awesome pipeline. We're looking to publish a small study on the circulating Dengue viruses in the solomons. What is the best way to cite your work?

I was thinking of citing this preprint:

https://www.medrxiv.org/content/10.1101/2023.10.13.23296997v1

Does that work?

Thanks,

Ammar

**Comment by ViralVerity** [comment]
Yep! That's absolutely the right citation - it will hopefully be out of preprint form soon as well (it's going through final publication changes)
