### ISSUE TITLE
How to specify number of cores/cpus?

### ISSUE THREAD

**Issue by ammaraziz** [grubaughlab/DENV_pipeline#19]
Hi there,

How do I specify number of cores for snakemake to use? There's the `--slurm-cores` flag but I am not running the pipeline on slurm system.

I tried specifying `--cores` through the cli and by creating a `config.yaml` file with `cores: 150` but these both failed with the same error: `denv_pipeline: error: unrecognized arguments: --cores 150`

Thanks,

Ammar

**Comment by ViralVerity** [comment]
Hi,

I have just added that feature! It should now work using the cli or the config file with the ```--cores``` argument.

Let me know if you have any issues

**Comment by ammaraziz** [comment]
Thank you for the insanely fast fix!
